### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by itdaboyz** [kpdean/RED_OPS_Better#4]
Hello,

RED_OPS_Better worked for 40~ releases but then I have this error:

```
Traceback (most recent call last):
  File "/home/cyril/RED_OPS_Better/./red_ops_better", line 421, in <module>
    main()
  File "/home/cyril/RED_OPS_Better/./red_ops_better", line 279, in main
    artist = group['group']['musicInfo']['artists'][0]['name']
IndexError: list index out of range
```

If I reload RED_OPS_Better with cache, it crash at first try. Without cache, it checks for the 40~ releases done before and crash after.

Any idea?

**Comment by itdaboyz** [comment]
Fixed.
The problematic album had no artist name and no composer name as it was a DJ remix.

Replace line 267 to take DJ credits.
```
            artist = "";
            if len(group['group']['musicInfo']['artists']) > 2:
                artist = "Various Artists"
            elif not group['group']['musicInfo']['artists'] and len(group['group']['musicInfo']['composers']) > 2:
                artist = "Various Artists"
            elif len(group['group']['musicInfo']['artists']) == 2:
                artist = group['group']['musicInfo']['artists'][0]['name'] + " & " + group['group']['musicInfo']['artists'][1]['name']                
            elif not group['group']['musicInfo']['artists'] and len(group['group']['musicInfo']['composers']) == 2:
                artist = group['group']['musicInfo']['composers'][0]['name'] + " & " + group['group']['musicInfo']['composers'][1]['name']         
            elif not group['group']['musicInfo']['artists'] and len(group['group']['musicInfo']['composers']):
                artist = group['group']['musicInfo']['composers'][0]['name']
            elif not group['group']['musicInfo']['artists'] and not group['group']['musicInfo']['composers'] and len(group['group']['musicInfo']['dj']):
                artist = group['group']['musicInfo']['dj'][0]['name']
            else:
                artist = group['group']['musicInfo']['artists'][0]['name']
```
