### ISSUE TITLE
ModuleNotFoundError: No module named 'mutagen' despite pip saying the requirement is satisfied

### ISSUE THREAD

**Issue by Fluff663** [kpdean/RED_OPS_Better#6]
Output of ./red_ops_better
Traceback (most recent call last):
  File "./red_ops_better", line 13, in <module>
    import tagged
  File "/home1/fluff663/RED_OPS_Better/tagged.py", line 30, in <module>

    import mutagen
ModuleNotFoundError: No module named 'mutagen'
fluff663@white:~/RED_OPS_Better$ ./red_ops_better
Traceback (most recent call last):
  File "./red_ops_better", line 13, in <module>
    import tagged
  File "/home1/fluff663/RED_OPS_Better/tagged.py", line 30, in <module>
    import mutagen
ModuleNotFoundError: No module named 'mutagen'
fluff663@white:~/RED_OPS_Better$ ./red_ops_better --help
Traceback (most recent call last):
  File "./red_ops_better", line 13, in <module>
    import tagged
  File "/home1/fluff663/RED_OPS_Better/tagged.py", line 30, in <module>
    import mutagen
ModuleNotFoundError: No module named 'mutagen'
fluff663@white:~/RED_OPS_Better$ pip3 install mutagen
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mutagen in /home1/fluff663/.local/lib/python3.8/site-packages (1.46.0)
fluff663@white:~/RED_OPS_Better$ python3 ./red_ops_better --help
Traceback (most recent call last):
  File "./red_ops_better", line 13, in <module>
    import tagged
  File "/home1/fluff663/RED_OPS_Better/tagged.py", line 30, in <module>
    import mutagen
ModuleNotFoundError: No module named 'mutagen'
fluff663@white:~/RED_OPS_Better$ ls
config_Example  __pycache__  README.md  RedOpsAPI.py  red_ops_better  requirements.txt  tagged.py  transcode.py
fluff663@white:~/RED_OPS_Better$ nano requirements.txt
fluff663@white:~/RED_OPS_Better$ python3 ./red_ops_better --help
Traceback (most recent call last):
  File "./red_ops_better", line 13, in <module>
    import tagged
  File "/home1/fluff663/RED_OPS_Better/tagged.py", line 30, in <module>
    import mutagen
ModuleNotFoundError: No module named 'mutagen'

Output of pip3 install mutagen
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mutagen in /home1/fluff663/.local/lib/python3.8/site-packages (1.46.0)

**Comment by Fluff663** [comment]
also running as sudo isnt an option as this is a shared seedbox
