### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by Fluff663** [kpdean/RED_OPS_Better#7]
Password Must include Minimum length (10), Capital and lower letter, number and special character
Provide a Password for Encry and Decrp: 
Logging in to Redacted....
WARNING: session cookie attempted and failed
Traceback (most recent call last):
  File "/home/fluff663/RED_OPS_Better/RedOpsAPI.py", line 83, in _login
    self._login_cookie()
  File "/home/fluff663/RED_OPS_Better/RedOpsAPI.py", line 95, in _login_cookie
    r = self.session.open(mainpage)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/mechanicalsoup/stateful_browser.py", line 148, in open
    resp = self.get(url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/mechanicalsoup/browser.py", line 149, in get
    response = self.session.get(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fluff663/RED_OPS_Better/./red_ops_better", line 421, in <module>
    main()
  File "/home/fluff663/RED_OPS_Better/./red_ops_better", line 231, in main
    api = RedOpsAPI.RED_OPS_API(username, password, session_cookie, endpoint, args.totp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/RED_OPS_Better/RedOpsAPI.py", line 78, in __init__
    self._login()
  File "/home/fluff663/RED_OPS_Better/RedOpsAPI.py", line 86, in _login
    self._login_username_password()
  File "/home/fluff663/RED_OPS_Better/RedOpsAPI.py", line 110, in _login_username_password
    r = self.session.post(loginpage, data=data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/mechanicalsoup/browser.py", line 163, in post
    response = self.session.post(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fluff663/.local/lib/python3.11/site-packages/requests/sessions.py", line 191, in resolve_redirects
    raise TooManyRedirects(
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by Fluff663** [comment]
It turned out i was grabbing the cookie from the wrong location in firefox.

**Comment by slickgslickg** [comment]
> It turned out i was grabbing the cookie from the wrong location in firefox.

Hi, where were you getting it from, and what solved the error? I'm having the same issue. Cheers.
